### ISSUE TITLE
Docs/examples

### ISSUE THREAD

**Issue by jotaf98** [joshcox/kanren#4]
This looks pretty cool! Any chance of having a few short examples to kick off development by casual users like me?

**Comment by joshcox** [comment]
@jotaf98, sure thing! I'll shoot to get some examples written and documented thoroughly here soon.

After I get #3 figured out, I'll be able to define some recursive relations. As the library currently stands, there unfortunately isn't much you can do past simple unification of terms.

**Comment by jotaf98** [comment]
Awesome! Well simply composing and/or clauses, and unification, can already express matching of many fancy structures, so it's useful already.

I agree that recursive relations would be nice for more advanced applications, looking forward to it!

**Comment by joshcox** [comment]
@jotaf98, feel free to check out #5.

**Comment by jotaf98** [comment]
Awesome, thanks! This is pretty clear. In case you want some feedback, I'd say the only bit that could use some further explanation is the callWithFresh function, as it's slightly surprising when you see it the first time (but it's not a showstopper, it's certainly possible to understand it from context!).

**Comment by joshcox** [comment]
The feedback's appreciated. I added a lead up sentence to introduce `callWithFresh` before the reader sees the usage. Also added a couple comments for the first usage of `callWithFresh` to try to show the process of using a variable within a goal and wrapping it with `callWithFresh`. Thoughts?

**Comment by jotaf98** [comment]
Yep I think this improves it quite a lot! It should cover everything that's needed for most kinds of pattern matching. I think it's safe to close this issue (as it was asking for getting-started examples).
